openapi: 3.0.3
info:
  title: Notifications
  contact:
    name: API Support
    url: https://example
    email: koposov-andrej@mail.ru
  version: 1.0.0
  description: Notifications service
servers:
  - url: /api/v1
tags:
  - name: notifications
    description: tag-notifications
paths:
  /notifications/{id}:
    get:
      tags:
        - notifications
      operationId: getNotification
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\NotificationsController@get'
      x-lg-route-name: 'getNotification'
      x-lg-skip-request-generation: true
      summary: Получение объекта типа Notification
      description: Получение объекта типа Notification
      parameters:
        - $ref: '#/components/parameters/PathId'
        - $ref: '#/components/parameters/QueryInclude'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - notifications
      operationId: putNotification
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\NotificationsController@replace'
      x-lg-route-name: 'putNotification'
      x-lg-skip-request-generation: true
      summary: Обновление объекта типа Notification
      description: Обновление объекта типа Notification
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        description: replaceNotificationRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationPostBody'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - notifications
      operationId: patchNotification
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\NotificationsController@patch'
      x-lg-route-name: 'patchNotification'
      x-lg-skip-request-generation: true
      summary: Обновление полей объекта типа Notification
      description: Обновление полей объекта типа Notification
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        description: replaceNotificationRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationPostBody'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - notifications
      operationId: deleteNotification
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\NotificationsController@delete'
      x-lg-route-name: 'deleteNotification'
      x-lg-skip-request-generation: true
      summary: Удаление объекта типа Notification
      description: Удаление полей объекта типа Notification
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/DeleteResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
  /notifications:
    post:
      tags:
        - notifications
      operationId: createNotification
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\NotificationsController@add'
      x-lg-route-name: 'createNotification'
      x-lg-skip-request-generation: true
      summary: Создание объекта типа Notification
      description: Создание объекта типа Notification
      requestBody:
        description: createNotificationRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationPostBody'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
  /types/{id}:
    get:
      tags:
        - types
      operationId: getType
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\TypesController@get'
      x-lg-route-name: 'getType'
      x-lg-skip-request-generation: true
      summary: Получение объекта типа NotificationType
      description: Получение объекта типа NotificationType
      parameters:
        - $ref: '#/components/parameters/PathId'
        - $ref: '#/components/parameters/QueryInclude'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationTypeResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
    delete:
      tags:
        - types
      operationId: deleteNotificationType
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\TypesController@delete'
      x-lg-route-name: 'deleteNotificationType'
      x-lg-skip-request-generation: true
      summary: Удаление объекта типа NotificationType
      description: Удаление полей объекта типа NotificationType
      parameters:
        - $ref: '#/components/parameters/PathId'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/DeleteResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
    put:
      tags:
        - types
      operationId: putNotificationType
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\TypesController@replace'
      x-lg-route-name: 'putNotificationType'
      x-lg-skip-request-generation: true
      summary: Обновление объекта типа NotificationType
      description: Обновление объекта типа NotificationType
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        description: replaceNotificationTypeRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationTypePostBody'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
    patch:
      tags:
        - types
      operationId: patchNotificationType
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\TypesController@update'
      x-lg-route-name: 'patchNotificationType'
      x-lg-skip-request-generation: true
      summary: Обновление полей объекта типа NotificationType
      description: Обновление полей объекта типа NotificationType
      parameters:
        - $ref: '#/components/parameters/PathId'
      requestBody:
        description: replaceNotificationTypeRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationTypePostBody'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
  /types:
    post:
      tags:
        - types
      operationId: createNotificationType
      x-lg-handler: 'App\Http\ApiV1\Modules\Notifications\Controllers\TypesController@add'
      x-lg-route-name: 'createNotificationType'
      x-lg-skip-request-generation: true
      summary: Создание объекта типа NotificationType
      description: Создание объекта типа NotificationType
      requestBody:
        description: createNotificationTypeRequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NotificationTypePostBody'
      responses:
        "200":
          description: Успешный ответ
          content:
            application/json:
              schema:
                $ref: './customers.yaml#/NotificationTypeResponse'
        "404":
          $ref: '#/components/responses/NotFound'
        "500":
          $ref: '#/components/responses/ServerError'
components:
  parameters:
    QueryInclude:
      $ref: './common_parameters.yaml#/QueryInclude'
    PathId:
      $ref: './common_parameters.yaml#/PathId'
  schemas:
    EmptyDataResponse:
      type: object
      properties:
        data:
          type: object
          nullable: true
        meta:
          type: object
      required:
          - data
    PaginationTypeEnum:
      $ref: './common_schemas.yaml#/PaginationTypeEnum'
    NotificationPostBody:
      $ref: './common_schemas.yaml#/NotificationPostBody'
    NotificationTypePostBody:
      $ref: './common_schemas.yaml#/NotificationTypePostBody'
  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    NotFound:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
    ServerError:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: './errors.yaml#/ErrorResponse'
